# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SpyPipeGRPC.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SpyPipeGRPC.proto',
  package='spy_pipe_pkg',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11SpyPipeGRPC.proto\x12\x0cspy_pipe_pkg\"(\n\x04\x44\x61ta\x12\x0f\n\x07payload\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontrol\x18\x02 \x01(\t2G\n\x0bSpyPipeGRPC\x12\x38\n\x08SendData\x12\x12.spy_pipe_pkg.Data\x1a\x12.spy_pipe_pkg.Data\"\x00(\x01\x30\x01\x62\x06proto3'
)




_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='spy_pipe_pkg.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='spy_pipe_pkg.Data.payload', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='control', full_name='spy_pipe_pkg.Data.control', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=75,
)

DESCRIPTOR.message_types_by_name['Data'] = _DATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), {
  'DESCRIPTOR' : _DATA,
  '__module__' : 'SpyPipeGRPC_pb2'
  # @@protoc_insertion_point(class_scope:spy_pipe_pkg.Data)
  })
_sym_db.RegisterMessage(Data)



_SPYPIPEGRPC = _descriptor.ServiceDescriptor(
  name='SpyPipeGRPC',
  full_name='spy_pipe_pkg.SpyPipeGRPC',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=77,
  serialized_end=148,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendData',
    full_name='spy_pipe_pkg.SpyPipeGRPC.SendData',
    index=0,
    containing_service=None,
    input_type=_DATA,
    output_type=_DATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SPYPIPEGRPC)

DESCRIPTOR.services_by_name['SpyPipeGRPC'] = _SPYPIPEGRPC

# @@protoc_insertion_point(module_scope)
