# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import SpyPipeGRPC_pb2 as SpyPipeGRPC__pb2


class SpyPipeGRPCStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendData = channel.stream_stream(
                '/spy_pipe_pkg.SpyPipeGRPC/SendData',
                request_serializer=SpyPipeGRPC__pb2.Data.SerializeToString,
                response_deserializer=SpyPipeGRPC__pb2.Data.FromString,
                )


class SpyPipeGRPCServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendData(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpyPipeGRPCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendData': grpc.stream_stream_rpc_method_handler(
                    servicer.SendData,
                    request_deserializer=SpyPipeGRPC__pb2.Data.FromString,
                    response_serializer=SpyPipeGRPC__pb2.Data.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'spy_pipe_pkg.SpyPipeGRPC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SpyPipeGRPC(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendData(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/spy_pipe_pkg.SpyPipeGRPC/SendData',
            SpyPipeGRPC__pb2.Data.SerializeToString,
            SpyPipeGRPC__pb2.Data.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
